filter/braille/filters/musicxmltobrf.in, filter/braille/filters/texttobrf.in
We need to make sure to use the brf table first, in case the table being
used defines other display encodings.
=> braille: make sure liblouis emits pure BRF output

drv/generic-brf.drv, drv/indexv3.drv, drv/indexv4.drv, mime/braille.convs, mime/braille.types
When using a text/ MIME type, detection for .brf files would always
discover text/plain, instead of text/vnd.cups-brf, thus preventing from
directly embossing files by running .brf. Using application/vnd.cups-brf
avoids detection from trying to be too smart.
=> braille: use application/vnd.cups-brf instead of text/vnd.cups-brf

.gitignore
Add  `filter/braille/filters/brftopagedbrf` to `.gitignore` since this file is automatically generated by [`filter/braille/filters/brftopagedbrf.in`](https://github.com/OpenPrinting/cups-filters/blob/master/filter/braille/filters/brftopagedbrf.in)
=> .gitignore: Add 'filter/braille/filters/brftopagedbrf'

Makefile.am
cups checks only for executability and writability, while checksumming tools
need to be able to read files easily.
=> Do not remove read permission on cups-brf

filter/pdf.cxx
This only fails with >=poppler-0.67.0 but the change to const was done
in 0.64.0
Closes: #50
=> GooString needs to be const since >=poppler-0.64.0

COPYING, Makefile.am, filter/bannertopdf.c, filter/pdf.cxx, filter/pdf.h
**Introduction**
This pull request caters to the project **["Improving bannertopdf filter to use QPDF instead of Poppler APIs"](https://summerofcode.withgoogle.com/projects/#5640715745361920)** being done as a part of the **[Google Summer of Code Program](https://summerofcode.withgoogle.com/)**, 2018. 
Remove all Poppler code from `bannertopdf` and re-write it using QPDF.
Fixes #8.
Depends on https://github.com/qpdf/qpdf/issues/178 for completion.
=> Rewrite bannertopdf to use QPDF instead of Poppler

filter/pdftoijs.cxx, filter/pdftoopvp/pdftoopvp.cxx, filter/pdftoraster.cxx
Poppler v0.70 made some parameters/return values const. Due to this fact the build now fails.
This PR adapts the corresponding variables and therefore fixes the build.
Tested with poppler v0.70.1 and gcc v8.2.0.
Furthermore it fixes #69
=> Fix build with poppler >= 0.70

utils/cups-browsed.c, utils/cups-browsed.conf.5, utils/cups-browsed.conf.in
Hi Till,
I created for https://bugzilla.redhat.com/show_bug.cgi?id=1648697 feature to cups-browsed, about which we talked in #71 - cups-browsed will skip printers, which had N unsuccessful tries for print queue creation due timeouts during print queue creation, until restart of service.
I created HttpMaxRetries directive for possible manual settings of HttpMaxRetries (possible values > 0), defaults to 5. 
Does it look fine?
Zdenek
=> Introduce HttpMaxRetries directive

cupsfilters/image.c, cupsfilters/image.h, filter/imagetopdf.c, filter/imagetoraster.c, filter/pdftopdf/pdftopdf.cc, filter/pdftopdf/pdftopdf_processor.cc, filter/pdftopdf/pdftopdf_processor.h, filter/pdftopdf/qpdf_pdftopdf_processor.cc, filter/pdftopdf/qpdf_pdftopdf_processor.h
Related to #65 .
For this functionality, the input file has to cover the entire page. I first cropped input file according to the page's aspect ratio after that normal processing is done.
```imagetopdf``` and ```imagetoraster``` uses ```convert``` command(ImageMagick) to crop the input file.
```pdftopdf``` filter uses qpdf to crop the given pdf.
Is there any improvement that needs to be done in this PR?
=> Added print-scaling=fill functionality.

filter/pdftopdf/pdftopdf.cc, filter/pdftopdf/pdftopdf_processor.cc, filter/pdftopdf/pdftopdf_processor.h, filter/pdftopdf/qpdf_pdftopdf_processor.cc, filter/pdftopdf/qpdf_pdftopdf_processor.h
Bug fix for #92. 
When the input format is other than "pdf"(like ps) and ```pdftopdf``` filter chain is being used then ```pdftopdf``` is unable to automatically set the orientation for crop-to-fit and fill options. When orientation is not set, the is_landscape function is used to check orientation of the input file.
=> Set orientation for crop-to-fit and fill in pdftopdf.

.gitignore, cupsfilters/image-gif.c, cupsfilters/image.c
Fixes #81. Fixes #82. Some checks are added so that program exits gracefully. Checks are added according to the input files given by @ocean1. Return type of flush_tile() function is changed to int.
=> Add checks for processing gif.

utils/cups-browsed.c
The code tried to remove trailing spaces, but if there was
at least one trailing space, the last two characters of the
line were removed. This caused removal of the quotation mark
in case exactly one trailing space was present, breaking
the PPD and subsequently causing CUPS to mess up all queues
(even local ones).
Signed-off-by: Oliver Freyermuth <o.freyermuth@googlemail.com>
=> cups-browsed: Fix broken trailing space removal on "NickName".

filter/urftopdf.cpp
Doxygen throws a warning: warning: the name `urf_decode.cpp' supplied as the second argument in the \file statement is not an input file
this is corrected. The information should be correct regardless whether or not it is used.
=> Correct comment

Makefile.am, backend/implicitclass.c, cupsfilters/pdftoippprinter.c, cupsfilters/pdftoippprinter.h, cupsfilters/ppdgenerator.c, cupsfilters/ppdgenerator.h, utils/cups-browsed.c, utils/driverless.c
- cups-browsed doesn't download ppd directly from the server for the remote cups queue, the ppd is generated from the IPP request.
- cups-browsed treats IPP Network printer and remote cups queue equally
- We can cluster IPP Network printer and remote cups queue, Now we can cluster any arbitrary printers.
- Implicitclass backend changed completely, now it sends jobs to the IPP backend.
- Wrote functions for generating merged attributes of the cluster and the constraints for the cluster.
- cups-browsed auto selects the printer in the cluster based on the job attributes supplied.
- New filter pdftoippprinter added which converts pdf file to the format supported by the printer.
=> Content Oriented Printer AutoSelection

utils/cups-browsed.c
- The ppd file will be changed and new options will be added/deleted in the file on addition/deletion of new printers.
- Improved the debug statements which print the merged options of the cluster.
=> Recreating cluster's ppd file on addition/deletion of printers

filter/foomatic-rip/foomaticrip.c
vfprintf was segfaulting because it was trying to interpret
the %s with a missing argument.
=> Fix argument representation for raw queue debug mesaage.

Makefile.am, autogen.sh, configure.ac
texttotext.c uses iconv so it should link with libiconv on platforms
where it is a separate library (e.g. uClibc-ng without built-in NLS)
otherwise texttotext fails to link:
CCLD     texttotext
[...]/ld: texttotext-texttotext.o: in function `main':
texttotext.c:(.text.startup+0xde0): undefined reference to `libiconv_open'
[...]/ld: texttotext.c:(.text.startup+0xf9d): undefined reference to `libiconv'
[...]/ld: texttotext.c:(.text.startup+0xfd6): undefined reference to `libiconv'
[...]/ld: texttotext.c:(.text.startup+0x16c3): undefined reference to `libiconv_close'
Modify autogen.sh to call autopoint, which adds the libiconv discovery.
It also creates a "po" skeleton but we can discard it, since it is not
really necessary.
Fixes: https://bugs.busybox.net/show_bug.cgi?id=12031 …
=> filter/texttotext.c: link with libiconv if needed

m4/ac_ln_srf.m4
Use "ln -s -r -f" to ensure that existing symlinks are overritten.
Signed-off-by: Carlos Santos <unixmania@gmail.com>
=> install: fix reinstallation of driverless and foomatic-rip

Makefile.am
Some integration tools (e.g. Buildroot) run autoreconf to re-generate
the configure script. Ensure that the files config.rpath and ABOUT-NLS
are provided. They are required because we gettextized cups-filters to
detect libiconv.
Signed-off-by: Carlos Santos <unixmania@gmail.com>
=> Build system: support autoreconf

utils/cups-browsed.c
cups-browsed leaks http_t structure in get_printer_attributes().
Reported by valgrind:
==126994== 1,623,360 (1,593,264 direct, 30,096 indirect) bytes in 114 blocks are definitely lost in loss record 1,197 of 1,198                              
==126994==    at 0x483BB1A: calloc (vg_replace_malloc.c:762)                                                                                                
==126994==    by 0x4C5342E: http_create (http.c:3969)                                                                                                       
==126994==    by 0x4C5668C: httpConnect2 (http.c:446)                                                                                                       
==126994==    by 0x40AD68: httpConnectEncryptShortTimeout (cups-browsed.c:1166) …
=> Fix leaks in get-printer-attributes

utils/cups-browsed.c
Turns out our printer returns "server-error-version-not-supported " with a trailing white space. This pull request fixes this problem.
=> remove whitespaces from printer message

utils/cups-browsed.c
In `examine_discovered_printer_record`, the `location` parameter is ensured not to be `NULL`.  However, when checking whether to update the location from the DNS-SD TXT record note field, it is checked for being a `NULL` pointer.  Since all invocations seem to default to the empty string instead of `NULL`, the check is adjusted accordingly.
=> cups-browsed: Fix unset location check to use DNS-SD field

utils/cups-browsed.c
Hi Till,
this is basically the same commit as #91 , but for the code you mentioned at first time - breaking from loop if the queue is remote should do the trick (cups-browsed at least creates correct print queue and printing is ok).
Would you mind adding it to the project too and prevent bogus errors?
=> Do not set printer-is-shared for remote queue vol. 2

backend/implicitclass.c, utils/cups-browsed.c
The fallback is required in three cases : 
1. Some printers doesn't support "media-col-database", so in that case we can do a IPP2.0 request without asking for media-col-database. In this case the ipp status returned is `IPP_STATUS_ERROR_BAD_REQUEST`.
2. Some printer doesn't support IPP2.0 and return error `IPP_STATUS_ERROR_VERSION_NOT_SUPPORTED`, so in this case we do a IPP1.1 request.
3. In some case, the ipp status is null, but still no information is returned from the printer, the printer only returns `attributes-natural-language` and `attribute charset`, in this case, we can do one of the above fallback to get better output.
*Implementation*
First we do a normal IPP 2.0 request with requested attributes {"all", "media-col-database"}, if it fails we do a IPP1.1 request, and if that …
=> cups-browsed,implicitclass: Do fallback without mediacol

filter/foomatic-rip/foomaticrip.c, filter/foomatic-rip/options.c
Starting from the upcoming GCC release 10, the default of -fcommon option will
change to -fno-common. This causes compilation errors in foomatic-rip. These
seem to be due to missing "external" declarations.
https://gcc.gnu.org/onlinedocs/gcc-9.2.0/gcc/Code-Gen-Options.html#index-fno-common
=> foomatic-rip: fix compilation with -fno-common

cupsfilters/ppdgenerator.c
over pwg-raster-document-type-supported
For #186
=> Prioritize print-color-mode-supported during creating Color Models

Makefile.am, filter/pdf.cxx, filter/pdf.h, filter/pdftops.c
pdftops filter exits with value 0 on empty input and zero page pdf and with value 1 on broken, damaged and wrong format input files and PS is considered a wrong format input for the pdftops filter to ensure similar behaviour for all filters accepting pdf as input.
=> pdftops: added handling of empty input

configure.ac, filter/test_pdf2.c, fontembed/test_analyze.c, fontembed/test_pdf.c, fontembed/test_ps.c
Hi Till,
Font team in Fedora changed naming of fonts in Fedora, so now default test font in test suite is not found, but test binaries or configure script do not check if it exists and binaries segfault instead.
Old font path:
/usr/share/fonts/dejavu/DejaVuSans.ttf
New font path:
/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf
I'm not sure if the change will be in other distros, so I fixed it by supplying new path to configure script, but the segfault if the font is not supplied does not seem as correct result.
The pull request fixes the segfault and adds the check in configure.ac - the configuration will end with error if the font file is not found.
Would you mind adding it to the project?
=> Fix segfaults in test suite when test font is missing

utils/cups-browsed.c
Hi Till,
I found several other possible memory leaks in cupsAddOption() calls - using strdup as parameter of cupsAddOption() results in losing the allocated pointer, because cupsAddOption() allocates the memory by itself and since the pointer allocated by strdup is not saved anywhere, it leaks.
Plus I assigned NULL into response pointer too, because it is in the loop and the garbage after freeing can confuse the conditional when getting new response fails.
I tested it in Fedora rawhide and I was able to see remote print queues and print to one of them.
Would you mind adding the fix into the project?
Thank you in advance,
Zdenek
=> Fix possible memory leaks in cups-browsed daemon

utils/driverless.c
The call to unlink(2) in "driverless" used the wrong variable,
triggering a silent failure (ENAMETOOLONG), and leaving a temporary file
behind.
=> driverless: Unlink temporary file

utils/cups-browsed.c, utils/cups-browsed.conf.5, utils/cups-browsed.conf.in
Hi Till,
The directive `NewBrowsePollQueuesShared` which shares printers discovered by the browse poll directive is added in the method `browse_poll_get_printers` as here it was already being checked for printers discovered by BrowsePoll directive.
Kindly let me know if this patch requires any modifications.
=> cups-browsed: Added AllowResharingRemoteCUPSPrinters directive to cups-browsed

configure.ac
== is a bash-specific test operator.  Use = here for portability.
=> Replace '==' in configure.ac test with '='

filter/foomatic-rip/foomaticrip.c, filter/foomatic-rip/pdf.c, filter/foomatic-rip/renderer.c, filter/gstoraster.c, filter/pdftopdf/pdftopdf.cc
Hi Till,
I talked with Chris Lidell a week ago and he told me -dPARANOIDSAFER option, which cups-filters use, is the same as -dSAFER and -dPARANOIDSAFER is deprecated in ghostscript, so in my opinion we can move to use -dSAFER. There were some differences in the past - ~2007 - but it is no longer true for some time and now they provide the same functionality.
Would you mind adding the patch into the project?
=> Use -dSAFER gs option

filter/pdftops.c
Hi Till,
there is a report https://github.com/apple/cups/issues/5765 which led me to this pull request. In my opinion it would be good to mention the README debug log speaks of is cups-filters README, not CUPS - even when the log appears to be in CUPS logs.
Would you mind adding the patch to the project?
=> Mention cups-filters in pdftops debug log

cupsfilters/ppdgenerator.c, utils/cups-browsed.c
Hi Till,
I did an other round of valgrind testing of cups-browsed and found out several other issues with memory (leaks, conditional jump on uninitialized value), which the pull request fixes.
Would you mind adding it into the project?
=> Fix memory issues in ppdgenerator, cups-browsed

filter/gstoraster.c, filter/rastertopdf.cpp
Passing NULL to printf-family of functions is undefined
behaviour. OpenBSD has detection mechanism for occurrences
of such condition. On my machine I get following messages
in syslog, while printing:
vfprintf %s NULL in "DEBUG: OUTFORMAT="%s", so output format will be %s "
Changes in this diff make those messages go away.
=> Do not pass NULL to fprintf()

cupsfilters/ipp.c, cupsfilters/ipp.h, utils/driverless.c
Hi,
I encountered this problem several times during debugging printing issues with older printers - the device is capable to advertise itself via Avahi but its IPP response is not enough for CUPS temporary queue, either if it does not support IPP 2.0 or it's missing some required attributes.
Fortunately those printers can be driverless with help of cups-browsed, which has those two fallbacks available so even older IPP printers can be supported as driverless.
The problem is when you run 'sudo lpinfo -l -v', driverless backend says 'driverless' in device-info text - but it indicates only the device is available on avahi-browse, because driverless backend calls ippfind tool for the job and it just checks Avahi.
So you don't know (until you try to install it with 'everywhere' model) if the …
=> [RFE] Check for driverless support and set device-info accordingly

configure.ac
Fixes #239 - AS_IF has support for cross-platform compilation.
=> configure.ac: Use AS_IF instead of AC_CHECK_FILE for font check

filter/foomatic-rip/foomaticrip.c
two-sided-short-edge and two-sided-long-edge were both mapped to
DuplexNoTumble.  DuplexNoTumble should be mapped to the long-edge
tumble and short-edge to DuplexTumble.
=> Map two-sided-short-edge to DuplexTumble

Makefile.am, filter/pclmtoraster.cxx, mime/cupsfilters.convs.in
I have added the new `pclmtoraster` which converts `pclm` files to raster. Currently the following colorspaces are tested and supported :
cmyk, rgb, srgb, adobergb, black (1 Bit), and sgray.
Currently, conversion from one colorspace to another is not supported.
Some test reports are available [here](https://github.com/V1krant/test-reports).
=> Add pclmtoraster filter

utils/cups-browsed.8
Hi,
man page of cups-browsed mentions the absolute path to README and AUTHORS files, which can be different due packaging the project.
Currently, I have a downstream patch in Fedora for renaming the path and Ubuntu seems to duplicate README, NEWS, copyright files to both packages - cups-browsed and cups-filters - just into different dirs, which seems unnecessary for doc files.
In my opinion it would be the best just to remove the misleading entries from cups-browsed man page and stop duplicating files/stop carrying a downstream patch. The doc files will be available once in main location, /usr/share/doc/cups-filters.
Would it be okay?
=> cups-browsed.8: Remove mentions of README and AUTHORS files

utils/cups-browsed.c
This PR modifies when to call cupsGetNamedDest(). 
Now instead of calling cupsGetNamedDest() for every printer , we first do a get-printer-attribute IPP request on local cupsd and check if we have CUPS queue with that name. If found then we call cupsGetNamedDest().
=> modified when to call cupsGetNamedDest()

utils/cups-browsed.c
Hi,
the patch is connected to what we discussed in #241  - to have gnome-settings-daemon ignoring cups-browsed queues.
In case of temp queues, cups-browsed is setting/resetting printer-is-shared attribute to make them permanent. The problem is, cups is generating 'printer-added' notification during the operation, and gnome-settings-daemon catches it and generates pop-up notification.
The solution is to add ```cups-browsed``` option to the print queue during setting/resetting printer-is-shared attribute. 
IMO it will not cause a regression, since the option is applied only on successful request to cups, mid-way state (one request passes, the other fails) will end up as error either way, and cups is prone of duplicate options, there is no chance of two ```cups-browsed``` options if both …
=> Mark the temp queue as cups-browsed during setting printer-is-shared

filter/imagetoraster.c
Fix a potential NULL dereference, when PPD file isn't present or can't be openned
=> Potential null dereference fix (#1)

configure.ac
Cross-compilation is broken since commit 1d66106. Indeed, when
cross-compiling, dejavu font won't be installed in /usr/share/fonts. The
path (e.g. $(TARGET_DIR)/usr/share/fonts/dejavu/DejaVuSans.ttf) could be
provided through --with-test-font-path which will fix the build failure
but will result in broken test programs.
So when cross-compiling don't try to check if the test-font-path is
valid or not and just use the one provided by the user or the default
one (e.g. /usr/share/fonts/dejavu/DejaVuSans.ttf)
Fix #262
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix cross-compilation without dejavu

utils/cups-browsed.c, utils/cups-browsed.conf.5, utils/cups-browsed.conf.in
Currently debug logging was not checking for the size of the debug file it has produced. The amount of logging could go to huge extents and cause issues such as filling up entire disk if proper control of file is taken care of.
Adding two log files which alternate between them helps to resolve the issue in 2 ways:
- Does not create mulitple backup logs which may, again, cause the disk to be full of logs.
- Does not allow the size of the cups-browsed_log to go beyond a particular size which can be set in the source code file.
Fixes #260
=> changes in cups-browsed.c file to produce back-up file for debug logging

utils/driverless.1, utils/driverless.c
Currently `driverless` list only IPP printers . Adding `_ipps._tcp` argument to driverless. 
The below command would list  the driver URIs and metadata for all available IPPS printers supporting driverless printing.
`driverless _ipps._tcp` 
Fixes [#251](https://github.com/OpenPrinting/cups-filters/issues/251)
EDIT: Now, `driverless` shows IPPS queues whenever the printer supports it and IPP queues when the printer does not support IPPS. 
`driverless _ipps._tcp` shows only IPPS printer URI
`driverless _ipp._tcp` shows only IPP printer URI.
I have tested with `ippeveprinter` and it was giving results as expected.
=> changes in driverless.c file to list IPPS printers

utils/driverless.c
Testing results:
```
nidhi@nidhi-X510UNR:~$ driverless _ipps._tcp
ipps://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipps._tcp.local/
ipps://hello1._ipps._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless _ipp._tcp
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D%20(USB%201)._ipp._tcp.local/
ipp://hello1._ipp._tcp.local/
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipp._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless 
ipps://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipps._tcp.local/
ipps://hello1._ipps._tcp.local/
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D%20(USB%201)._ipp._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless list
DEBUG: Started ippfind (PID 24180)
"driverless:ipps://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipps._tcp.local/" en "HP" "HP OfficeJet Pro 6960, fully …
```
=> Updating driverless

utils/driverless.1, utils/driverless.c
Testing results
```
nidhi@nidhi-X510UNR:~$ driverless dns-sd-off
ipps://HP30E171C3B82D.local:443/ipp/print
ipp://HP30E171C3B82D.local:631/ipp/print
ipp://localhost:60000/ipp/print
nidhi@nidhi-X510UNR:~$ driverless _ipps._tcp dns-sd-off
ipps://HP30E171C3B82D.local:443/ipp/print
nidhi@nidhi-X510UNR:~$ driverless _ipp._tcp dns-sd-off
ipp://HP30E171C3B82D.local:631/ipp/print
ipp://localhost:60000/ipp/print
```
=> Added command line option to show uris in standard form

utils/driverless.c
=> driverless.c: accept clean ipp uris too for 'driverless cat'

utils/driverless.c
Testing results:
```
nidhi@nidhi-X510UNR:~$ driverless
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D%20(USB%201)._ipp._tcp.local/
ipps://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipps._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless _ipps._tcp
ipps://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipps._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless _ipp._tcp
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D._ipp._tcp.local/
ipp://HP%20OfficeJet%20Pro%206960%20%5BC3B82D%5D%20(USB%201)._ipp._tcp.local/
nidhi@nidhi-X510UNR:~$ driverless --std-ipp-uris
ipp://HP30E171C3B82D.local:631/ipp/print
ipp://localhost:60000/ipp/print
ipps://HP30E171C3B82D.local:443/ipp/print
nidhi@nidhi-X510UNR:~$ driverless list
DEBUG: Started ippfind (PID 19293)
DEBUG: Started ippfind (PID 19294) …
```
=> driverless.c: make the two ippfind tasks(for IPP and  IPPS) run in parallel.

utils/driverless.c
time taken after creating two more forks to read output of each ippfind call simultaneously
```
nidhi@nidhi-X510UNR:~$ time driverless
ipps://hello._ipps._tcp.local/
ipps://hello1._ipps._tcp.local/
ipps://hello2._ipps._tcp.local/
real	0m3.224s
user	0m0.029s
sys	0m0.027s
nidhi@nidhi-X510UNR:~$ time driverless list
DEBUG: Started ippfind (PID 18725)
DEBUG: Started ippfind (PID 18726)
DEBUG: Started reading ipp data (PID 18727)
DEBUG: Started reading ipps data (PID 18728)
"driverless:ipps://hello._ipps._tcp.local/" en "Example" "Example Printer, fully driverless, cups-filters 1.27.5" "MFG:Example;MDL:Printer;CMD:PWGRaster,AppleRaster,PWG,URF;"
"driverless:ipps://hello1._ipps._tcp.local/" en "Example" "Example Printer, fully driverless, cups-filters 1.27.5" …
```
=> driverless.c: creating two more forks to read output of each ippfind call simultaneously

utils/driverless.c
Memory cleanup after the last merge.
P.S. It can be an advantage if students are encouraged to use ```valgrind --leak-check=full``` when testing their PRs - it can find memory leaks and double free errors.
=> Free the used memory

cupsfilters/ipp.c, cupsfilters/ipp.h
=> driverless: Fix uninitialized buffer and parsing ippfind output

utils/cups-browsed.c
Hi,
valgrind [results](https://bugzilla.redhat.com/attachment.cgi?id=1717802) in Fedora [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1881365) revealed that I didn't understand how ```ippFindAttribute()``` works when I issued a PR which clears ```response``` variable in ```get_printer_uuid()```. The ```ippFindAttribute()``` returns a pointer to a member of ```response``` structure and this pointer is freed when ```response``` is freed with ```ippDelete()```.
The fix now uses ```strdup()``` for the pointer and this copy is returned as return value.
=> cups-browsed.c: uuid was used after its pointer was freed by ippDelete()

filter/foomatic-rip/foomaticrip.c
print_file() foomatic-rip doesn't clean up the temporary file created when reading from stdin and a pdf-to-ps conversion is necessary.  The result is that `/var/spool/cups/tmp` can fill up very quickly on a busy system.
This should fix that.
=> foomatic-rip: remove tempfile created during pdf-to-ps conversion

filter/foomatic-rip/foomaticrip.c
If the foomatic rip command is not present in the PPD file, the foomatic
rip filter runs cat by default to forward stdin to stdout. However,
if input is provided through a file instead of stdin, then this file
needs to be dup'd to stdin for the command to work properly.
Also, the next file needs to be selected each time an input file is
processed by calling strok_r in order to prevent an infinite loop.
TEST=foomatic-rip --ppd=ppd.ppd file.pdf
=> Fix foomatic-rip infinite loop and file input

cupsfilters/ppdgenerator.c, cupsfilters/ppdgenerator.h, utils/cups-browsed.c
I ran cups-browsed in several scenarios within valgrind:
1) discovering a print queue from cupsd via legacy CUPS protocol
2) discovering a printer via Avahi
3) discovering a print queue via Avahi and via legacy CUPS protocol at the same time -> cups-browsed creates a cluster
4) printing via print queue which was discovered via legacy CUPS protocol
5) printing via print queue discovered by Avahi
6) printing via cluster
and found several issues. They are fixed via changes below, each commit contains a description what was the problem and how it is fixed, if it is not obvious. Especially, please let me know of your opinion about fixing leaks within tag zero attributes.
I tested it manually (checking valgrind results and if printing went ok) and via our internal CI, and the tests passed. …
=> Various browsed issues

filter/pdftopdf.c
Upon running pdftopdf filter, 
`DEBUG: pdftopdf: No FINAL_CONTENT_TYPE environment variable, could not determine whether to log pages or not, so turned off page logging.`
This Debug statement was being printed. This was because in pdftopdf.c , NULL was being sent to the parameters argument instead of the final output type. 
So the fix is to send `OUTPUT_FORMAT_PDF` in the argument, instead of NULL.
=> pdftopdf : Fix no final_content_type environment variable found bug

backend/implicitclass.c
For the convenience in communication with the printer, when the network is too busy that cups-browsed is not able to respond within the time limit, couldn't we increase the usleep() time or no. of loops in implicitclass to make it from 20 sec to 60 sec in order to work in all conditions and modes.
=> implicitclass: 20s policy

NEWS, utils/cups-browsed.service
cups-browsed can be set to browsepolling remote servers, browsing remote
queues via CUPS protocol or sharing local queues via CUPS protocol.
Although sharing and browsing happens via browsesocket (which can be
solved by setting socket option IP_FREEBIND), browsepolling must have
network working to communicate with a remote server.
Would you mind adding the PR to the project?
=> utils/cups-browsed.service: Add network-online.target

filter/pdftoraster.cxx
This PR is related to the bug :- https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1920190 
RAM(4 GB) improves from 32% usage to 7% for pdftoraster filter.
=> Pdftoraster: free colour data after processing of each page

utils/cups-browsed.c, utils/cups-browsed.conf.5, utils/cups-browsed.conf.in
The PR implements two things:
1) NotifLeaseDuration directive for cups-browsed.conf - it will make
lease duration for notifications configurable by users. IMO it is not
useful for regular users, but it is helpful during sanity testing
(for verifying that we actually renew the subscription when time
comes). The current hardcoded 1 day is unusuable for that :( .
I implemented the lowest threshold to 300s to prevent a possible DoS.
2) Subscription renewal is set to happen in the middle of NotifLeaseDuration,
not one minute before lease expiration. This was a problem on busy servers,
where cups-browsed was busy and wasn't able to renew the subscription
before cupsd removed it. Then if some jobs had come before the subscription
was created again, the queue got disabled. The proposed approach …
=> cups-browsed.c: Introduce NotifLeaseDuration directive

cupsfilters/ghostscript.c, cupsfilters/imagetopdf.c, cupsfilters/imagetops.c, cupsfilters/pclmtoraster.cxx, cupsfilters/pdftoraster.cxx, cupsfilters/raster.c, cupsfilters/raster.h, filter/mupdftoraster.c, filter/textcommon.c
1. Ghostscript (gstopxl, gstoraster, gstopdf) now PPD file independent.
2. Updated cupsRasterParseIPPOptions to support Job-attrs.
3. Made cupsRasterPrepareHeader PPD file independent.
I will soon write an alternative function ppdRasterInterpretPPD which uses printer-attrs instead of PPD file and will make its use wherever needed.
Thanks
=> ghostscript filters(gstopxl, gstoraster, gstopdf) now PPD file independent.

cupsfilters/pdftopdf/pdftopdf.cc
Trying to print a page range using a command like "`lp -P 10- /etc/services`" doesn't work because pdftopdf doesn't properly recognize the print option that results from the command (`page-ranges=10-2147483647`).  Pdftopdf translates `page-ranges=10-2147483647)` to `[1,inf)` instead of `[10,inf)`.
=> pdftopdf: Fix page ranges like "10-2147483647"

filter/braille/drivers/index/textbrftoindexv3.in
'-' does not work with $'\000' actually, so we have to filter it out
separately.
=> textbrftoindex: Fix control character filtering

Makefile.am
Add missing line continuation character in libcupsfilters-la_LIBADD
stanza. This fixes `make[2]: lm: No such file or directory` errors while
building.
Move fontembed library before fontembed library, this fixes
`/usr/bin/ld: cannot find -lfontembed` errors during install. This may
just be a workaround for dependency resolving issues elsewhere.
[0] - https://github.com/OpenPrinting/cups-filters/issues/419
=> Fix issues with build described in 419

cupsfilters/ipp.c
RFC7472 requires that 'ipps' must be used over HTTPS, but driverless
does not enforce encryption and will use insecure connection by
default. This makes it unusable with a printer that expects secure
connection only on 'ipps' port.
=> driverless: Always use encryption for ipps

configure.ac
Removing dejavu- dependency from cups filter 
fixes #411 
changing error message to a warning so that cups filter can be installed without deja vu
=> removing dejavu -dependency

cupsfilters/ghostscript.c, cupsfilters/imagetopdf.c, cupsfilters/imagetoraster.c
In some files, the input data stream is opened but not closed after the filter function returns, if it is unable to copy the input data to a tempfile.
See issue #437.
So issue is now solved by shutting the data stream when the filter function returns with an error
=> Missing closing file in some functions 

filter/braille/filters/vectortopdf.in
Removed/changed inkscape command-line arguments in recent releases breaks `/usr/lib/cups/filter/vectortopdf` which is used by the **CUPS Braille filter**. This commit checks the inkscape version and calls it with suitable arguments.
Fixes #315
=> vectortopdf: check inkscape version before calling inkscape

cupsfilters/pdftopdf/pdftopdf.cc, cupsfilters/pdftopdf/pdftopdf_processor.cc, cupsfilters/pdftopdf/pdftopdf_processor.h
Added orig-page-range option in pdftopdf filter which will provide more flexibility to the user for printing pages in a certain range. Unlike the existing page-range option, which applies the page-range parameter to the document after it has been processed, the orig-page-ranges option applies page-range before the document has been processed.
This option will also help in the solving the need of user as mentioned in issue #365.
=> Added option input-page-ranges in pdftopdf filter

Makefile.am
When compiling from source `sudo make install` fails to relink libppd because it depends on libcupsfilters, not yet installed.
Reordering the declarations in the Makefile.am and correcting the assignments of lib_LTLIBRARIES, check_PROGRAMS and TESTS fix the behavior.
To reproduce the issue try on a minimal Ubuntu environment, such as WSL or cloud images running on LXD or docker:
```
sudo apt install autotools-dev autoconf automake autopoint libavahi-client-dev libavahi-glib-dev libcurl4-gnutls-dev libglib2.0-dev libgnutls28-dev libjpeg-dev libpam0g-dev libpng-dev libusb-1.0-0-dev zlib1g-dev libcups2-dev libcupsimage2-dev libssl-dev libtool libqpdf-dev poppler-utils libfontconfig1-dev libpoppler-cpp-dev libtiff5-dev libdbus-1-dev libexif-dev librsvg2-bin sharutils liblcms2-dev ghostscript …
```
=> Moves the libppd declarations after cups-filters in Makefile.am

configure.ac, utils/cups-browsed.c, utils/cups-browsed.conf.5, utils/cups-browsed.conf.in
In case clients use BrowsePoll to a server with many queues or there is many printers on the local network, updating network interfaces after every found record slow cups-browsed a lot (f.e. on Fedora this step takes about 2-3s second for every queue). This PR adds FrequentNetifUpdate configure option and directive, which can turn off this update when we examine found records - the network interface update based on NM DBUS notification is not affected with this directive.
Would you mind adding it to the project?
Thank you in advance!
=> Add FrequentNetifUpdate option/directive

filter/foomatic-rip/foomaticrip.c, filter/foomatic-rip/options.c, filter/foomatic-rip/postscript.c, filter/rastertoescpx.c, utils/driverless.c
Hi Till,
I did a coverity scan for cups-filters during the rebase and the following
[issues](https://github.com/OpenPrinting/cups-filters/files/10757883/coverity-important-issues-detail.txt) were found - I fixed them by commits in this PR - would you mind merging it?
=> Coverity fixes for 2.0b3

filter/foomatic-rip/postscript.c
https://autopkgtest.ubuntu.com/packages/f/foo2zjs/lunar/ppc64el shows foo2zjs's testsuite failing with cups-filters 2.0beta3 on ppc64el because the gs command here to check page count is failing with a SIGPIPE when trying to write back to the parent.  To fix this, we close gs's input fd as soon as we know we're done writing to it.  Since gs may not have started processing its input until this happens, also give the final poll() a longer timeout (5s instead of 1s); without this we see race conditions because foomatic-rip gives up before gs has had a chance to finish processing.
=> fix a SIGPIPE error when calling gs

mime/cupsfilters-universal-postscript.convs
Unfortunately there are filters which produce this MIME type (such as hpps from hplip), and if someone uses such driver on client and server has IPP Everywhere/driverless driver, job fails.
The patch (together with change in libcupsfilters, which will come later) fixes the issue.
=> Enable application/vnd.cups-postscript in conversion tables

configure.ac
This was originally searched for cups-browsed, and during the great split these lookups accidentally got left in and moved around in the file.
The original code began with this autoconf comment:
```
dnl Avahi for cups-browsed
```
After shifting down, it became:
```
dnl Avahi
```
After removing avahi from configure.ac, there are no remaining mentions of avahi anywhere other than CHANGES*.md
Fixes #556
=> configure.ac: remove final traces of avahi

configure.ac
After carefully using configure checks designed to work on pre-unix wars bourne shells -- that is, the `test "$var" = ""` construct once upon a time wasn't specified to treat "" as a distinct argument, so the "x" padding provided a guaranteed comparison -- the configure.ac check then fails to run on any shells at all other than GNU bash.
Bash provides the standard `test XXX = YYY` or `[ XXX = YYY ]` utilities. It also provides the ability to spell the equals sign as a double equals. This does nothing whatsoever -- it adds no new functionality to bash, it forbids nothing, it is *literally* an exact alias.
It should never be used under any circumstances. All developers must immediately forget that it exists. Using it is non-portable and does not work in /bin/sh scripts such as configure …
=> configure: fix broken bashism resulting in logic failure

Makefile.am
As this is a C program, set
`pclmtoraster_CFLAGS`, not `pclmtoraster_CXXFLAGS`.
This fixes building pclmtoraster when libcupsfilter headers are installed in a non-standard directory.
Previously, when configuring and installing libcupsfilters with e.g. `--prefix=$HOME/temp/cpdb` and then configuring cups-filters with `PKG_CONFIG_PATH=$HOME/temp/cpdb/lib/pkgconfig/`, `make pclmtoraster` would fail like this:
CC       filter/pclmtoraster.o
filter/pclmtoraster.c:14:10: fatal error: cupsfilters/filter.h: No such file or directory
14 | #include <cupsfilters/filter.h>
|          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
For this to actually work, recent libcupsfilters
commit [1] is also needed:
commit 449ac6350d00c385ae226513ef6d85ee81ae161a
Author: Michael Weghorn <m.weghorn@posteo.de> …
=> pclmtoraster: Properly set CFLAGS

filter/braille/filters/cups-braille.sh.in, filter/braille/filters/liblouis1.defs.gen.in
Since version 3.21.0 liblouis uses language/region instead of locale.
=> braille: Fix picking locale from newer liblouis files

backend/serial.c
The comments aren't properly protected leading to the following error: backend/serial.c:822:16: error: expected ';' after expression
* devices
=> serial backend: unbreak build on BSD

filter/pdftopdf/qpdf_xobject.cc
Backport of fix [#56](https://github.com/OpenPrinting/libcupsfilters/pull/56/) in libcupsfilters to branch 1.x.
=> Backport data stream concatenation fix from libcupsfilters

cupsfilters/ppdgenerator.c
PPD files generated by `ppdgenerator.c` always contain a fixed `*DefaultDuplex: None` line.
This PR generates an entry based on the value of the IPP `sides-default` attribute, instead.
=> Set DefaultDuplex value to reflect sides-default attribute

filter/pdftoraster.cxx
C++17 removed dynamic exception specifications [1] they had been deprecated since C++11, replace
throw(whatever) with noexcept(false).
[1] https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0003r5.html
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> use noexcept(false) instead of throw() from c++17 onwards

filter/foomatic-rip/process.h
The newest standard has more strict data type checks, function pointers in function prototypes have to declare data types of its arguments.
=> Fix build failure with GCC 15 and -std=c23

.gitignore, Makefile.am, configure.ac, mime/cupsfilters-individual.convs.in
Add `--enable-texttopdf` and `--disable-texttopdf` configure options to determine whether to build this filter or not (and add the associated mime conversion type).  If this option is not specified, the default will be to build this filter (so this works the same prior to this change).
See https://github.com/OpenPrinting/libcupsfilters/pull/83 for a related change in libcupsfilters.
=> Add a configure option for texttopdf filter

cupsfilters/image-sgi.c
sgiOpenFile can fail when passing an image that both has large dimensions and which also uses RLE compression.  In that case, sgiOpenFile attempts to allocate space for compression-related tables and these allocations may fail due to the requested size, causing sgiOpenFile to return NULL.  Without this fix, the NULL pointer gets dereferenced, which crashes the filter process.
Compare https://en.wikipedia.org/wiki/Silicon_Graphics_Image#Header for an overview of the SGI image headere.
=> image-sgi: Return early if sgiOpenFile fails

Makefile.am, README.md, configure.ac, filter/foomatic-rip/foomatic-hash.1, filter/foomatic-rip/foomatic-hash.c, filter/foomatic-rip/foomatic-rip.1.in, filter/foomatic-rip/foomaticrip.c, filter/foomatic-rip/foomaticrip.h, filter/foomatic-rip/options.c, filter/foomatic-rip/process.c, filter/foomatic-rip/process.h, filter/foomatic-rip/util.c, filter/foomatic-rip/util.h
The PR provides a way for users to have control over what values are allowed for foomatic-rip related PPD keywords FoomaticRIPCommandLine, FoomaticRIPCommandLinePDF, and FoomaticRIPOptionSetting. Since the values can be later used when constructing shell command, the filter foomatic-rip was a target of several exploits (caused by issue at different place in CUPS or in different project of printing stack) to do arbitrary code execution when the filter is started.
By default the filter is run by user lp, so the issue is mitigated, but this PR gives admin complete control over what can be run in foomatic-rip and reject anything injected into system via different ways.
First, the new tool - foomatic-hash - can be called on a PPD file or directory with drivers/PPDs, with scan output and file …
=> Introduce foomatic-hash and reject unauthorized values in foomatic-rip

configure.ac, mime/cupsfilters-individual.convs.in, mime/cupsfilters-universal.convs, mime/cupsfilters.types
This pull request introduces new MIME type definitions and conversion rules to enable proper recognition of JPEG‑XL files in cups‑filters. With these changes, CUPS and associated utilities (e.g. cupsfilter) will be able to correctly identify and process JPEG‑XL files based on their content and file extension.
> **Note:** This PR is limited to MIME type contributions only and does not include changes to image decoding or filter implementations.
---
- **File Modified:** `mime/cupsfilters.types`
- Added a new MIME type entry for JPEG‑XL:
- The rule uses a magic signature check (for both the standard signature and the stream signature) to detect JPEG‑XL files. The `priority(150)` was added to ensure that this MIME type has a higher priority compared to similar image formats, so that JPEG‑XL …
=> Add MIME Type Definitions for JPEG‑XL Support

cupsfilters/raster.c
There were two identical `pwgMediaForPPD` calls.
=> raster: fix parsing PWG legacy media names
