filter/braille/drivers/index/textbrftoindexv3.in

This fixes some issues with embossing BRF-ready files.

Fix embossing BRF files

---

filter/braille/filters/texttobrf.in

in case the user didn't notice

braille: Warn when not text translation was selected

---

backend/beh.c
cupsfilters/colormanager.c
cupsfilters/image-sgilib.c
cupsfilters/image-sun.c
cupsfilters/ppdgenerator.c
cupsfilters/raster.c
filter/bannertopdf.c
filter/foomatic-rip/foomaticrip.c
filter/foomatic-rip/options.c
filter/foomatic-rip/spooler.c
filter/pdftops.c
filter/pdftoraster.cxx
filter/rastertoescpx.c
filter/rastertops.c
filter/sys5ippprinter.c
utils/cups-browsed.c
utils/driverless.c

Hi Till,
I ran static analysis by coverity scan for cups-filters-1.20.0, which we have in Fedora 28, and fixed several issues which were reported and they are even in current version. I'll send you initial results of scan by email (in case there are some issues, which can be exploitable).
Does it look good to you? Would you mind adding it to the project?

Fixing covscan issues

---

utils/cups-browsed.c

Hi Till,
I have a report in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1648697 , where cups-browsed time outs on connection to local CUPS before finishing creation of queue and causes high CPU load on cupsd process.
I am aware of httpLocalTimeout directive, which can set timeout for the connection and it fixes the issue, but I'm concerned about how fast retry of queue creation happens - TIMEOUT_RETRY is set 10s, but the retry happens in 3s or 4s after reaching timeout, which causes high load in CUPS.
It is caused by incorrect current time value in update_printer_queues(), which is defined at the start of function, and never refreshed after that, so it might happen cups-browsed floods cupsd with requests, because intervals between retries are short, because daemon spent some amount …

Keep actually current time for timeouts

---

filter/pdftops.c

Fixes #96 : pdftops - Force monochrome/grayscale PostScript output if job is to be printed in monochrome/grayscale.

---

filter/imagetopdf.c
filter/imagetoraster.c
filter/pdftopdf/pdftopdf.cc
filter/pdftopdf/pdftopdf_processor.cc
filter/pdftopdf/pdftopdf_processor.h

Support for the print-scaling feature has been added to imagetoraster, imagetopdf and pdftopdf filters.
Fixes #108.

Add support for print-scaling option.

---

backend/implicitclass.c
cupsfilters/ppdgenerator.c
utils/cups-browsed.c

- Corrected code styling for "for" and "if"
- Handling dup() status in the implicitclass backend

Corrected Code Styling

---

filter/pdftoraster.cxx

Fixes offset issues leading to segmentation faults in pdftoraster

---

filter/pdftopdf/qpdf_pdftopdf_processor.cc

Do not preserve encryption, since it already goes into printer

---

utils/cups-browsed.c

Hi,
we had an important issue in RHEL/Fedora about cups-browsed not closing http sockets to local CUPS in on_job_state(), which led into CUPS denial of service (MaxClient of cupsd was reached). I checked the latest upstream code and found out following issues:
1) httpConnectEncryptShortTimeout was removed from on_job_state(), but LoadBalancing on servers still needs http connection to remote server through http variable - currently it stays NULL and connection to remote server does not work. The patch puts it back, sets the correct 'if' and free the socket.
2) missing several cleanup of 'response' struct
The pull request fixes it, would you mind adding it to the project?

Fix leaks of ipp_t struct and load balancing on the servers

---

filter/rastertoescpx.c
filter/rastertopclx.c
filter/rastertops.c

Also fixed segmentation fault in rastertops when input file isn't found

rastertoescpx and rastertopclx: added handling of empty input

---

charset/pdf.utf-8.simple
filter/texttopdf.c

Modified charset file and texttopdf filter to add support for CJK fonts.

added support for CJK fonts

---

utils/cups-browsed.c

Initialize the value, add further checks, freeing memory and stop
allocating magic numbers.
Hi Till,
we got following report in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1802969 - cups-browsed was crashing in check_printer_with_option due uninitialized string.
I added several checks to the function code too.
Would you mind merging it?

Fix crash in check_printer_with_option

---

filter/foomatic-rip/foomaticrip.c

- reuse existing code for copying file, count pdf pages.
- remove temp file after processing.
Fixes: 37b7d6467dcd ("foomatic-rip: correct handling of jobs")
Signed-off-by: Andrey Jr. Melnikov <temnota.am@gmail.com>

Small cleanup

---

filter/foomatic-rip/foomaticrip.c
filter/foomatic-rip/pdf.h
filter/foomatic-rip/postscript.c

Used copy_file() function and moved zero-page handling to postscript.c

foomatic-rip: minor code changes

---

filter/pclmtoraster.cxx

Support for colorspace conversions has been added for pclm and raster pdfs with `DeviceRGB`, `DeviceCMYK`, and `DeviceGray` colorspaces.
Test reports can be found [here](https://github.com/V1krant/test-reports).

Add support for colorspace conversions in pclmtoraster filter

---

filter/pdf.cxx

when /mediabox is inherited from parent, can't get rect. the function getInheritableFieldValue(key) from QPDF dosen't know if key is inheritable.

fix: get inheritable attribute from parent

---

utils/cups-browsed.c

Hi,
we got an [issue in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1867412) - cups-browsed accumulates memory when it is run for long time (up to 1.3GB after a day of running). 
[This memory report](https://github.com/OpenPrinting/cups-filters/files/5088515/cups2.log) was collected by attaching to the process by gdb and leak check was run.
The log showed several CUPS arrays weren't freed at all (or its pointer was rewritten by another allocation in next loop iteration), several non-freed char arrays and non-freed ```ipp_t``` structures.
The pull request was tested by reporter and he didn't report any significant leakage after a day.
Would you mind adding the pull request to the project?
Thank you in advance,
Zdenek

cups-browsed.c: Fix several memory leaks

---

utils/cups-browsed.c

cups-browsed.c: fix compiler warnings

---

Makefile.am
utils/driverless-fax.in

See #292 , this is for master branch.

driverless-fax: don't use a fixed path

---

utils/driverless.c

Hi,
the latest driverless commit doesn't clean up an allocated memory and uses magic number. I added several notes to Nidhi's pull request about it, but he seems busy right now.
Would you mind adding the pull request to the project?
Thank you in advance!
Zdenek

driverless.c: free an allocated memory, use MAX_OUTPUT_LEN

---

cupsfilters/raster.c

So the issue is related to texttopdf filter. When we run it without a ppd file, it creates a pdf file with many no of pages, all empty. Below changes seems to work. 
@tillkamppeter  can you please review it. 
Thanks

margins updated texttopdf

---

utils/cups-browsed.c

…ord()'
The current code doesn't use rwlock in found_cups_printer() and
cupsdUpdateLDAPBrowse(), which causes deadlock when discovering queues
via BrowsePoll or LDAP.
It happens because the code in 'examine_discovered_printer_record()'
expects the rwlock to be locked already, so it unlocks the lock, calls
'get_local_queue_name()' and locks again.
The commit contains change '&(lock)' -> '&lock' too, it represents the
same thing, so we should use the same code for it.

utils/cups-browsed.c: Lock before all 'examine_discovered_printer_rec

---

utils/cups-browsed.c

Renamed ldap_connect() in cups-browsed.c

---

cupsfilters/ghostscript.c

fixed issue #354 
@tillkamppeter sir, can you please review this
many thanks

made changes to convert djvu files to printer's format faster

---

filter/texttotext.c

Thanks @tillkamppeter  sir for the support.
Now this PR is clean and nothing redundant in it.
I will be glad if you make some tests.
:-)

texttotext made PPD independent

---

filter/gstoraster.c

Refactor gstoraster a little to clarify handling of page counts and set job-impressions for TotalPageCount in PWG-Raster header.

Set the counted pages as job-impressions for PWG-Raster

---

cupsfilters/ppdgenerator.c

Search wildcard tag for "media-type" and "media-type-supported".  The tag of these fields may be "IPP_TAG_KEYWORD" or "IPP_TAG_NAME".

Use wildcard tag search

---

Makefile.am
cupsfilters/bannertopdf.c
cupsfilters/filter.h
filter/bannertopdf.c

Bannertopdf converted into filter function.

---

cupsfilters/bannertopdf.c

@tillkamppeter  Please do review it and tell the required changes if any.
Thank you very much

bannertopdf made PPD independent

---

cupsfilters/ghostscript.c
cupsfilters/imagetoraster.c
cupsfilters/raster.c
cupsfilters/raster.h

@tillkamppeter  sir please review it.
Thank you very much

print-render support added in ghostscript and imagetoraster function

---

cupsfilters/image-bmp.c
cupsfilters/image-jpeg.c
cupsfilters/image-photocd.c
cupsfilters/image-png.c
cupsfilters/image-tiff.c
cupsfilters/image.c

Fixes part of #362 .
Changed the default DPI resolution to 200 as suggested in the issue.

Changed the default ppi from 128 to 200.

---

filter/braille/filters/cups-braille.sh.in

Liblouis 3.21 introduced +language: and +region: metadata fields, so let
us support them as well.

cups-braille: Support new table metadata
